FLEI_COLOR_ESC=$(printf '\033')
FLEI_COLOR_RED="${FLEI_COLOR_ESC}[0;31m"
FLEI_COLOR_BLUE="${FLEI_COLOR_ESC}[0;34m"
FLEI_COLOR_LIGHT_GREY="${FLEI_COLOR_ESC}[0;37m"
FLEI_COLOR_PINK="${FLEI_COLOR_ESC}[0;95m"
FLEI_COLOR_NC="${FLEI_COLOR_ESC}[0m" # No Color
